package app.calio.android.ui.theme

import androidx.compose.ui.graphics.Color

// Shadcn-inspired neutral colors - Light mode
val Background = Color(0xFFFFFFFF)
val Foreground = Color(0xFF0A0A0A)
val Card = Color(0xFFFFFFFF)
val CardForeground = Color(0xFF0A0A0A)
val Popover = Color(0xFFFFFFFF)
val PopoverForeground = Color(0xFF0A0A0A)
val Primary = Color(0xFF171717)
val PrimaryForeground = Color(0xFFFAFAFA)
val Secondary = Color(0xFFF5F5F5)
val SecondaryForeground = Color(0xFF171717)
val Muted = Color(0xFFF5F5F5)
val MutedForeground = Color(0xFF737373)
val Accent = Color(0xFFF5F5F5)
val AccentForeground = Color(0xFF171717)
val Destructive = Color(0xFFEF4444)
val DestructiveForeground = Color(0xFFFAFAFA)
val Border = Color(0xFFE5E5E5)
val Input = Color(0xFFE5E5E5)
val Ring = Color(0xFF0A0A0A)

// Dark mode colors
val DarkBackground = Color(0xFF0A0A0A)
val DarkForeground = Color(0xFFFAFAFA)
val DarkCard = Color(0xFF0A0A0A)
val DarkCardForeground = Color(0xFFFAFAFA)
val DarkPopover = Color(0xFF0A0A0A)
val DarkPopoverForeground = Color(0xFFFAFAFA)
val DarkPrimary = Color(0xFFFAFAFA)
val DarkPrimaryForeground = Color(0xFF171717)
val DarkSecondary = Color(0xFF262626)
val DarkSecondaryForeground = Color(0xFFFAFAFA)
val DarkMuted = Color(0xFF262626)
val DarkMutedForeground = Color(0xFFA3A3A3)
val DarkAccent = Color(0xFF262626)
val DarkAccentForeground = Color(0xFFFAFAFA)
val DarkDestructive = Color(0xFF7F1D1D)
val DarkDestructiveForeground = Color(0xFFFAFAFA)
val DarkBorder = Color(0xFF262626)
val DarkInput = Color(0xFF262626)
val DarkRing = Color(0xFFD4D4D4)